version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directories:
      - /
      - /sdk/rust/minecraft-macros
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
