(module
  (import "minecraft" "mc_command_utf8_result" (func $command (param i32 i32) (result i32)))
  (memory (export "memory") 1 2)
  (global $sp (export "__stack_pointer") (mut i32) (i32.const 1024))
  (data (i32.const 0) "probe\ff\0a")
  (func (export "ok") (result i32) i32.const 42)
  (func (export "stack") (result i32) global.get $sp)
  (func (export "stack_trap") i32.const 512 global.set $sp unreachable)
  (func (export "command") (result i32) i32.const 0 i32.const 5 call $command)
  (func (export "bad_utf8") (result i32) i32.const 5 i32.const 1 call $command)
  (func (export "bad_control") (result i32) i32.const 6 i32.const 1 call $command)
  (func (export "bad_bounds") (result i32) i32.const 65536 i32.const 5 call $command)
  (func (export "bad_length") (result i32) i32.const 0 i32.const 32768 call $command)
  (func (export "grow") (param i32) (result i32) local.get 0 memory.grow)
  (func (export "loop") (loop $again br $again))
  (func (export "loop_if") (loop $again i32.const 1 br_if $again))
  (func (export "loop_table") (loop $again i32.const 0 br_table $again $again))
  (func $recur (export "recursion") call $recur)
)
